// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NugetProjExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "NugetProjExtension.f516f62a-fe43-45c8-ac3e-b4f067cf7306";
        public const string Name = "NugetProjExtension";
        public const string Description = @"Push nuget package projectPush";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
